/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_usbtuner_UsbTunerInterface */

#ifndef _Included_com_android_usbtuner_UsbTunerInterface
#define _Included_com_android_usbtuner_UsbTunerInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_usbtuner_UsbTunerInterface_DEBUG
#define com_android_usbtuner_UsbTunerInterface_DEBUG 0L
#undef com_android_usbtuner_UsbTunerInterface_PROGRAM_NO_UNDEFINED
#define com_android_usbtuner_UsbTunerInterface_PROGRAM_NO_UNDEFINED -1L
#undef com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_OTHER
#define com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_OTHER 0L
#undef com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_AUDIO
#define com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_AUDIO 1L
#undef com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_VIDEO
#define com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_VIDEO 2L
#undef com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_PCR
#define com_android_usbtuner_UsbTunerInterface_FILTER_TYPE_PCR 3L
#undef com_android_usbtuner_UsbTunerInterface_PID_PAT
#define com_android_usbtuner_UsbTunerInterface_PID_PAT 0L
#undef com_android_usbtuner_UsbTunerInterface_PID_ATSC_SI_BASE
#define com_android_usbtuner_UsbTunerInterface_PID_ATSC_SI_BASE 8187L
#undef com_android_usbtuner_UsbTunerInterface_DEFAULT_TUNE_TIMEOUT_MS
#define com_android_usbtuner_UsbTunerInterface_DEFAULT_TUNE_TIMEOUT_MS 4000L
/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeFinalize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeTuneAtsc
 * Signature: (JILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeTuneAtsc
  (JNIEnv *, jobject, jlong, jint, jstring, jint);

/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeAddPidFilter
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeAddPidFilter
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeCloseAllPidFilters
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeCloseAllPidFilters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeStopTune
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeStopTune
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_android_usbtuner_UsbTunerInterface
 * Method:    nativeWriteInBuffer
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_usbtuner_UsbTunerInterface_nativeWriteInBuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
